2020-08-13 13:48:23,800 ERROR: Exception on /user/okaaay [GET] [in c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\python_projects\flask-project-one\app\routes.py", line 98, in user
    return render_template('user.html', user=user,
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\python_projects\flask-project-one\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\python_projects\flask-project-one\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\python_projects\flask-project-one\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\python_projects\flask-project-one\app\templates\user.html", line 21, in block "app_content"
    {{ form.hidden_tag() }}
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-08-13 13:50:14,291 INFO: Microblog startup [in E:\python_projects\flask-project-one\app\__init__.py:55]
2020-08-13 13:50:16,007 ERROR: Exception on /user/okaaay [GET] [in c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\tarlo\appdata\local\programs\python\python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\python_projects\flask-project-one\app\routes.py", line 97, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-08-13 13:50:53,207 INFO: Microblog startup [in E:\python_projects\flask-project-one\app\__init__.py:55]
2020-08-13 13:51:23,742 INFO: Microblog startup [in E:\python_projects\flask-project-one\app\__init__.py:55]
2020-08-13 13:52:52,194 INFO: Microblog startup [in E:\python_projects\flask-project-one\app\__init__.py:55]
2020-08-13 14:10:13,028 INFO: Microblog startup [in E:\python_projects\flask-project-one\app\__init__.py:56]
2020-08-13 14:13:10,187 INFO: Microblog startup [in E:\python_projects\flask-project-one\app\__init__.py:56]
